package com.mafoya.oja.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;

@Data
@DynamoDBTable(tableName = "OjaCard-hvlboaadvrhhpi7zd6mqvplo6e-devv")
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Card {
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute(attributeName = "createdAt")
    private Instant createdAt;
    @DynamoDBAttribute(attributeName = "title")
    private String title;
    @DynamoDBAttribute(attributeName = "amount1")
    private String amount1;
    @DynamoDBAttribute(attributeName = "amount2")
    private String amount2;
    @DynamoDBAttribute(attributeName = "color")
    private String color;
    @DynamoDBAttribute(attributeName = "percentage")
    private String percentage;

}
