package com.mafoya.oja.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.Instant;

@Data
@DynamoDBTable(tableName = "OjaCarousel-hvlboaadvrhhpi7zd6mqvplo6e-dev")
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Carousel {
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute(attributeName = "createdAt")
    private Instant createdAt;
    @DynamoDBAttribute(attributeName = "title")
    private String title;
    @DynamoDBAttribute(attributeName = "subTitle")
    private String subTitle;
    @DynamoDBAttribute(attributeName = "discount")
    private Integer discount;
    @DynamoDBAttribute(attributeName = "category")
    private String category;
    @DynamoDBAttribute(attributeName = "imgUrl")
    private String imgUrl;
    @DynamoDBAttribute(attributeName = "description")
    private String description;
    @DynamoDBAttribute(attributeName = "buttonText")
    private String buttonText;
    @DynamoDBAttribute(attributeName = "buttonLink")
    private String buttonLink;
    @DynamoDBAttribute(attributeName = "playStoreLink")
    private String playStoreLink;
    @DynamoDBAttribute(attributeName = "appStoreLink")
    private String appStoreLink;
}
