package com.mafoya.oja.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.mafoya.oja.helper.ObjectConverter;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;
import java.util.Set;

@Data
@DynamoDBTable(tableName = "OjaCategoryItem-hvlboaadvrhhpi7zd6mqvplo6e-dev")
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CategoryItem {
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "createdAt")
    private Instant createdAt;
    @DynamoDBAttribute(attributeName = "icon")
    private String icon;
    @DynamoDBAttribute(attributeName = "title")
    private String title;
    @DynamoDBAttribute(attributeName = "href")
    private String href;
    @DynamoDBAttribute(attributeName = "categoryItemId")
    private String categoryItemId;
    @DynamoDBAttribute(attributeName = "categoryNavigationId")
    private String categoryNavigationId;

}


