package com.mafoya.oja.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.mafoya.oja.helper.ObjectConverter;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;
import java.util.Set;

@Data
@DynamoDBTable(tableName = "OjaCategoryNavigation-hvlboaadvrhhpi7zd6mqvplo6e-dev")
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CategoryNavigation {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "createdAt")
    private Instant createdAt;
    @DynamoDBAttribute(attributeName = "category")
    private String category;
    @DynamoDBTypeConverted(converter = ObjectConverter.class)
    @DynamoDBAttribute(attributeName = "categoryItem")
    private Set<CategoryItem> categoryItem;
}
