package com.mafoya.oja.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;

@Data
@DynamoDBTable(tableName = "OjaEarning-6izfil7vl5a77cv7qdoaxmqwey-dev")
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Earning {
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute(attributeName = "createdAt")
    private Instant createdAt;
    @DynamoDBAttribute(attributeName = "no")
    private Integer no;
    @DynamoDBAttribute(attributeName = "sellerEarning")
    private Float sellerEarning;
    @DynamoDBAttribute(attributeName = "adminCommission")
    private Float adminCommission;
    @DynamoDBAttribute(attributeName = "orderNo")
    private String orderNo;
    @DynamoDBAttribute(attributeName = "shopName")
    private String shopName;
}
