package com.mafoya.oja.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;

@Data
@DynamoDBTable(tableName = "OjaPaymentPackage-hvlboaadvrhhpi7zd6mqvplo6e-dev")
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PaymentPackage {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "createdAt")
    private Instant createdAt;


    @DynamoDBAttribute(attributeName = "no")
    private String no;

    @DynamoDBAttribute(attributeName = "date")
    private Instant date;


    @DynamoDBAttribute(attributeName = "seller")
    private String seller;


    @DynamoDBAttribute(attributeName = "package")
    private String packages;

    @DynamoDBAttribute(attributeName = "amount")
    private String amount;

    @DynamoDBAttribute(attributeName = "payment")
    private String payment;


}
