package com.mafoya.oja.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;

@Data
@DynamoDBTable(tableName = "OjaVisitor-6izfil7vl5a77cv7qdoaxmqwey-dev")
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Visitor {
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute(attributeName = "name")
    private String name;
    @DynamoDBAttribute(attributeName = "createdAt")
    private Instant createdAt;
    @DynamoDBAttribute(attributeName = "stateName")
    private String stateName;
    @DynamoDBAttribute(attributeName = "page")
    private String page;
    @DynamoDBAttribute(attributeName = "siteName")
    private String siteName;
    @DynamoDBAttribute(attributeName = "city")
    private String city;
    @DynamoDBAttribute(attributeName = "countryName")
    private String countryName;
    @DynamoDBAttribute(attributeName = "countryCode")
    private String countryCode;
    @DynamoDBAttribute(attributeName = "postal")
    private String latitude;
    @DynamoDBAttribute(attributeName = "longitude")
    private String longitude;
    @DynamoDBAttribute(attributeName = "ip")
    private String ip;
}
