
server:
  port: '8083'
# AWS properties
aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION}
  endpoint: ${AWS_DYNAMODB_ENDPOINT}
  profile-name: ${AWS_PROFILE_NAME}

logging:
  level:
    org:
      springframework:
        web: DEBUG

spring:
  data:
    dynamodb:
      entity2ddl:
        writeCapacity: '1'
        readCapacity: '10'
        gsiProjectionType: ALL
        auto: create-only